name: Continuous Integration

on:
  pull_request:
    branches: [main, master]

jobs:
  ci-success:
    name: CI
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: password
          POSTGRES_DB: forumapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Set ENV variables for test
        run: |
          echo "DATABASE_URL=postgres://runner:password@localhost:5432/forumapi_test" >> $GITHUB_ENV
          echo "PGHOST_TEST=localhost" >> $GITHUB_ENV
          echo "PGUSER_TEST=runner" >> $GITHUB_ENV
          echo "PGPASSWORD_TEST=password" >> $GITHUB_ENV
          echo "PGDATABASE_TEST=forumapi_test" >> $GITHUB_ENV
          echo "PGPORT_TEST=5432" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}" >> $GITHUB_ENV
          echo "REFRESH_TOKEN_KEY=${{ secrets.REFRESH_TOKEN_KEY }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_AGE=3000" >> $GITHUB_ENV
      - name: Run Database Migration
        run: npm run migrate:test

      - name: Run All Tests
        run: npm test
        env:
          NODE_OPTIONS: "--experimental-modules" 
          ACCESS_TOKEN_AGE: 3000